global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    monitor: 'codelab-monitor'


scrape_configs:
  - job_name: open5gs-amfd
    scrape_interval: 1s
    static_configs:
      - targets: ["10.0.0.1:9090"]
  - job_name: open5gs-smfd
    scrape_interval: 1s
    static_configs:
      - targets: ["10.0.0.1:9091"]
    